name: GUCCIPVP
version: 1.0
main: com.github.caaarlowsz.guccimc.kitpvp.Main
author: reacteey, iLucasUS
descripition: Nada :D
commands:
  kits:
  score:
  clicktest:
  setspawn:
  spawn:
  fps:
  glad:
  setglad:
  setfps:
  sortearvip:
  macrotest:
  kit:
  setarena:
  setknock:
  ranks:
  criarkit:
  knock:
  setvoid:
  void: 
  setskit:
  regras:
  sc:
  rdm:
  fakealeatorio:
  mdr:
  aplicar:
  setrdm:
  setmdr:
  setmlg:
  mlg:
  chat:
  skit:
  setchallenge:
  fake:
  challenge:
  ip:
  tag:
  gm:
  teleportall:
  tp:
  report:
  youtuber:
  dano:
  admin:
  autosoup:
  arena:
  build:
  ping: